# Generated by Django 3.2.10 on 2021-12-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_altertative_path_remove_file_full_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
